### ISSUE TITLE
GitHub Action expertise

### ISSUE THREAD

**Issue by szepeviktor** [dingo-d/test-action#1]
@dingo-d Ask a professional :) https://github.com/marketplace/actions/install-phive 👀

**Comment by szepeviktor** [comment]
These are my very first action twins.

**Comment by dingo-d** [comment]
I'm not sure what is this used for exactly? 

This repo is just for me to test out certain actions I'd like to work on 😄

**Comment by szepeviktor** [comment]
> I'm not sure what is this used for exactly?

This is the **very first** action of mine published on the Marketplace.

**Comment by dingo-d** [comment]
Oh, awesome! Congratz! 🙂  

I'll check it out in more details, and see if I can use it somewhere 🙂
